export type DiseaseMatch = {
  specialization: string;
  feeId: number;
};

type DiseaseEntry = DiseaseMatch & { terms: string[] };

const DISEASES: DiseaseEntry[] = [
  {
    specialization: "General Practitioner",
    feeId: 1,
    terms: [
      "fever", "fievre", "umuriro", "high fever", "umuriro mwinshi",
      "fatigue", "umunaniro", "weakness", "intege nke", "asthenie",
      "cold", "flu", "grippe", "ibicurane", "influenza", "common cold",
      "checkup", "check up", "isuzuma", "consultation generale", "bilan de sante", "general consultation",
      "chills", "gutitira", "frissons",
      "sore throat", "umuhogo", "mal de gorge", "pharyngite", "amygdalite", "tonsillitis",
      "runny nose", "nez qui coule", "sinusite", "sinusitis", "rhume",
      "body ache", "body pain", "courbatures", "ububabare bw umubiri",
      "earache", "ear pain", "otite", "mal d oreille", "ugutwi",
      "allergy", "allergie", "allergies", "hay fever", "rhume des foins",
      "dehydration", "deshydratation", "kumira",
      "loss of appetite", "anorexie legere", "kutarya",
      "swollen glands", "ganglions",
      "heat stroke", "coup de chaleur",
      "food poisoning", "intoxication alimentaire", "uburozi",
      "vitamin deficiency", "carence en vitamines",
      "general weakness", "malaise", "feeling unwell",
      "vaccination", "vaccine", "urukingo", "vaccin",
      "insect bite", "piqure", "mosquito bite",
      "wound", "blessure", "igikomere", "cut", "coupure",
      "snake bite", "morsure de serpent", "inzoka ikubise",
      "poisoning", "empoisonnement", "uburozi bw intoki",
      "nosebleed", "saignement de nez", "epistaxis", "amaraso mu mazuru",
      "hearing loss", "perte auditive", "tinnitus", "acouphenes", "kutumva",
      "toothache", "mal de dent", "rage de dent", "amenyo", "carie", "cavity",
      "swollen lymph nodes", "ganglions gonfles",
      "night sweats", "sueurs nocturnes",
      "unexplained weight loss", "perte de poids", "kugabanuka",
    ],
  },
  {
    specialization: "Internal Medicine",
    feeId: 2,
    terms: [
      "diabetes", "diabete", "diyabete", "isukari", "indwara y isukari", "diabete type 2", "diabete type 1", "type 2 diabetes", "type 1 diabetes",
      "high blood sugar", "hyperglycemia", "hyperglycemie", "isukari ryinshi",
      "low blood sugar", "hypoglycemia", "hypoglycemie",
      "hypertension", "umuvuduko w amaraso", "tension", "high blood pressure", "tension arterielle", "umuvuduko w amaraso uri hejuru",
      "anemia", "anemie", "iron deficiency", "carence en fer", "amaraso make",
      "cholesterol", "high cholesterol", "cholesterol eleve", "dyslipidemie",
      "thyroid", "thyroide", "goiter", "goitre", "hypothyroidism", "hypothyroidie", "hyperthyroidism", "hyperthyroidie",
      "gout", "goutte", "acide urique",
      "sickle cell", "drepanocytose", "sickle cell disease",
      "obesity", "obesite", "umubyibuho", "overweight",
      "metabolic syndrome", "syndrome metabolique",
      "chronic kidney disease", "insuffisance renale chronique",
      "lupus", "lupus erythemateux",
      "electrolyte imbalance",
      "leukemia", "leucemie", "lymphoma", "lymphome", "blood cancer", "cancer du sang",
      "thyroid cancer", "cancer de la thyroide", "thyroid nodule", "nodule thyroidien",
      "hashimoto", "graves disease", "maladie de basedow",
      "prediabetes", "prediabete", "diabetic", "sucre", "blood sugar", "glycemie",
      "low blood pressure", "hypotension", "tension basse", "umuvuduko w amaraso uri hasi",
      "high triglycerides", "triglycerides",
      "vitamin d deficiency", "carence en vitamine d", "vitamin b12",
      "polycythemia", "thalassemia", "thalassemie",
      "rheumatoid arthritis", "polyarthrite",
      "vasculitis", "vascularite",
    ],
  },
  {
    specialization: "Infectious Disease",
    feeId: 19,
    terms: [
      "malaria", "malariya", "paludisme", "malaria fever",
      "typhoid", "typhoide", "fievre typhoide", "typhoid fever",
      "hiv", "sida", "aids", "vih",
      "tuberculosis", "tb", "igituntu", "tuberculose",
      "covid", "covid 19", "coronavirus", "corona",
      "hepatitis", "hepatite", "hepatitis a", "hepatitis b", "hepatitis c", "hepatite b", "hepatite c",
      "cholera", "kolera",
      "measles", "rougeole", "seru",
      "chickenpox", "chicken pox", "varicelle",
      "mumps", "oreillons",
      "rubella", "rubeole",
      "dengue", "yellow fever", "fievre jaune",
      "meningitis", "meningite",
      "syphilis", "gonorrhea", "gonorrhee", "chlamydia", "herpes", "mpox", "monkeypox",
      "worms", "inzoka", "vers intestinaux", "intestinal worms", "parasites", "bilharzia", "bilharziose", "schistosomiasis",
      "amoeba", "amibe", "dysentery", "dysenterie",
      "tetanus", "tetanos", "rabies", "rage",
      "sepsis", "septicemie",
      "ebola", "brucellosis", "brucellose",
      "whooping cough", "coqueluche",
      "sexually transmitted infection", "ist", "mst",
      "hepatitis d", "hepatitis e", "hepatite d", "hepatite e", "hepatite a",
      "genital warts", "condylomes", "hpv", "papillomavirus",
      "trichomonas", "trichomonase",
      "scabies infection",
      "typhus",
      "polio", "poliomyelite",
      "diphtheria", "diphterie",
      "leprosy", "lepre",
      "anthrax", "charbon",
      "zika", "chikungunya",
      "flu like illness", "syndrome grippal",
      "opportunistic infection",
    ],
  },
  {
    specialization: "Cardiology",
    feeId: 17,
    terms: [
      "heart", "cardiac", "cardiology", "umutima", "coeur", "umutima urwaye",
      "chest pain", "ububabare bwo mu gatuza", "douleur thoracique", "angina", "angine de poitrine",
      "palpitations", "umutima uteragura", "palpitation",
      "heart failure", "heart attack", "infarctus", "myocardial infarction", "crise cardiaque",
      "arrhythmia", "arythmie", "tachycardia", "tachycardie", "bradycardia", "bradycardie",
      "atrial fibrillation", "fibrillation auriculaire",
      "heart murmur", "souffle au coeur",
      "cardiomyopathy", "cardiomyopathie",
      "coronary artery disease", "maladie coronarienne",
      "pericarditis", "pericardite",
      "high pulse", "low pulse",
      "swollen legs", "jambes gonflees", "edema", "oedeme",
      "varicose veins", "varices",
      "blood clot", "thrombose", "deep vein thrombosis",
      "heart disease", "maladie cardiaque", "indwara y umutima",
      "coronary", "angine", "ischemic heart", "cardiopathie ischemique",
      "heart valve", "valve cardiaque", "valvulopathie",
      "aortic stenosis", "retrecissement aortique",
      "endocarditis", "endocardite",
      "myocarditis", "myocardite",
      "cardiac arrest", "arret cardiaque",
      "chest pressure", "pression thoracique",
      "irregular heartbeat", "rythme irregulier",
      "low heart rate", "high heart rate",
      "heart pain", "douleur cardiaque", "ububabare bw umutima",
      "congenital heart", "cardiopathie congenitale",
      "hypertensive heart",
    ],
  },
  {
    specialization: "Pulmonology",
    feeId: 24,
    terms: [
      "asthma", "asima", "asthme", "asthma attack", "crise d asthme",
      "bronchitis", "bronchite", "bronchite chronique",
      "cough", "inkorora", "toux", "chronic cough", "toux chronique", "dry cough", "toux seche",
      "pneumonia", "pneumonie",
      "shortness of breath", "kubura umwuka", "essoufflement", "difficulte a respirer", "kubura umwuka uhagije",
      "copd", "bpco", "emphysema", "emphyseme",
      "wheezing", "sifflement",
      "lung infection", "infection pulmonaire",
      "tuberculosis cough",
      "pleural effusion", "epanchement pleural",
      "pulmonary embolism", "embolie pulmonaire",
      "sleep apnea", "apnee du sommeil",
      "lung fibrosis", "fibrose pulmonaire",
      "chest tightness", "poitrine serree",
      "smoker cough", "toux du fumeur",
      "lung cancer", "cancer du poumon", "kanseri y ibyuya",
      "lung disease", "maladie pulmonaire", "indwara z ibyuya",
      "tuberculosis of the lung",
      "bronchiectasis", "bronchectasie",
      "pulmonary hypertension", "hypertension pulmonaire",
      "pneumothorax",
      "respiratory failure", "insuffisance respiratoire",
      "chronic bronchitis",
      "allergic asthma", "asthme allergique",
      "coughing blood", "hemoptysie", "amaraso mu nkorora",
      "noisy breathing", "stridor",
      "oxygen shortage", "manque d oxygene",
    ],
  },
  {
    specialization: "Dermatology",
    feeId: 12,
    terms: [
      "eczema", "rash", "acne", "acné", "uruhu", "peau", "skin", "indwara z uruhu",
      "dermatitis", "dermatite",
      "psoriasis",
      "ringworm", "teigne", "tinea", "fungal skin", "mycose", "ibihute",
      "scabies", "gale", "agapfa",
      "hives", "urticaria", "urticaire",
      "vitiligo",
      "hair loss", "alopecia", "alopecie", "chute de cheveux", "gusiba imisatsi",
      "dandruff", "pellicules", "ibibibisha",
      "itching", "itchy skin", "demangeaison", "guheha", "kuraba",
      "boil", "furoncle", "abces", "abscess", "cellulitis", "cellulite infectieuse",
      "impetigo",
      "wart", "verrue", "warts",
      "shingles", "zona",
      "rosacea", "rosacee",
      "skin ulcer", "ulcere cutane",
      "athlete foot", "pied d athlete",
      "sunburn", "coup de soleil",
      "burn", "brulure", "kwaka",
      "keloid", "cheloide",
      "mole", "grain de beaute",
      "skin cancer", "cancer de la peau", "melanoma", "melanome",
      "dry skin", "peau seche",
      "sweat rash", "miliaire",
      "skin disease", "maladie de peau", "indwara y uruhu",
      "skin infection", "infection de la peau",
      "fungal infection", "infection fongique",
      "nail fungus", "onychomycose", "mycose des ongles",
      "contact dermatitis", "dermatite de contact",
      "atopic dermatitis", "dermatite atopique",
      "seborrheic dermatitis", "dermatite seborrheique",
      "lichen planus",
      "pemphigus",
      "bed sore", "escarre",
      "skin allergy", "allergie cutanee",
      "itchy rash", "eruption cutanee",
      "dark spots", "taches brunes", "hyperpigmentation",
      "white patches", "taches blanches",
      "boils", "furoncles",
      "herpes skin", "bouton de fievre", "cold sore",
      "measles rash",
    ],
  },
  {
    specialization: "Neurology",
    feeId: 6,
    terms: [
      "headache", "migraine", "kubabara umutwe", "mal de tete", "umutwe", "cephalee", "migraine headache",
      "seizure", "igicuri", "epilepsy", "epilepsie", "convulsion", "convulsions",
      "stroke", "avc", "accident vasculaire cerebral", "gutembera",
      "dizziness", "kuzungera", "vertige", "vertigo", "etourdissement",
      "parkinson", "parkinson disease", "maladie de parkinson",
      "alzheimer", "dementia", "demence", "memory loss", "perte de memoire", "kwibagirwa",
      "multiple sclerosis", "sclerose en plaques",
      "neuropathy", "neuropathie", "numbness", "tingling", "fourmillements", "engourdissement",
      "paralysis", "paralysie", "facial paralysis", "paralysie faciale",
      "bell palsy", "paralysie de bell",
      "tremor", "tremblement", "kujugumya",
      "concussion", "commotion cerebrale",
      "sciatica nerve", "nevralgie",
      "brain fog", "confusion",
      "fainting", "syncope", "evanouissement", "kuzimia",
      "brain tumor", "tumeur cerebrale", "cancer du cerveau",
      "brain disease", "maladie du cerveau", "indwara y ubwonko",
      "meningitis headache",
      "cluster headache", "cephalee en grappe",
      "tension headache", "cephalee de tension",
      "nerve pain", "douleur nerveuse", "nevralgie",
      "pinched nerve", "nerf coince",
      "carpal tunnel nerve",
      "guillain barre",
      "als", "sla", "motor neuron",
      "myasthenia", "myasthenie",
      "peripheral neuropathy", "neuropathie peripherique",
      "numb hands", "mains engourdies", "ibiganza byahumye",
      "numb feet", "pieds engourdis",
      "loss of balance", "perte d equilibre", "kuzungera",
      "speech difficulty", "difficulte a parler", "kudatinda kuvuga",
      "one side weakness", "faiblesse d un cote",
      "transient ischemic attack", "ait",
    ],
  },
  {
    specialization: "Psychiatry",
    feeId: 7,
    terms: [
      "depression", "anxiety", "anxiete", "agahinda", "ubwoba",
      "mental", "ubwenge", "psychiatry", "psychiatrie", "mental health", "sante mentale", "ubuzima bwo mu mutwe",
      "counseling", "ubujyanama", "conseil", "mental counseling", "psychotherapy", "psychotherapie",
      "bipolar", "bipolaire", "trouble bipolaire",
      "schizophrenia", "schizophrenie",
      "panic attack", "crise de panique", "crise d angoisse", "panic",
      "ptsd", "trauma", "traumatisme", "stress post traumatique",
      "stress", "stress au travail", "burnout", "epuisement",
      "insomnia", "insomnie", "kudakama", "cannot sleep", "trouble du sommeil",
      "addiction", "addiction a l alcool", "alcoolisme", "alcohol", "drug abuse", "toxicomanie",
      "ocd", "toc", "trouble obsessionnel",
      "adhd", "tdah", "hyperactivite",
      "autism", "autisme",
      "eating disorder", "anorexie", "anorexia", "boulimie", "bulimia",
      "psychosis", "psychose", "hallucination", "hallucinations",
      "grief", "deuil",
      "mood disorder", "trouble de l humeur",
      "mental illness", "maladie mentale", "indwara yo mu mutwe",
      "suicidal thoughts", "idees suicidaires",
      "self harm",
      "panic disorder", "trouble panique",
      "social anxiety", "anxiete sociale",
      "generalized anxiety", "anxiete generalisee",
      "postpartum depression", "depression post partum", "agahinda nyuma yo kubyara",
      "bipolar disorder",
      "schizophrenia disorder",
      "psychotic episode",
      "alcohol dependence", "dependance a l alcool", "inzoga",
      "drug dependence", "dependance aux drogues",
      "nicotine addiction", "tabagisme",
      "sleep disorder", "trouble du sommeil",
      "nightmare", "cauchemar",
      "anger problem", "probleme de colere",
      "counseling session", "ubujyanama mu mutwe",
    ],
  },
  {
    specialization: "Ophthalmology",
    feeId: 10,
    terms: [
      "eye", "eyes", "amaso", "oeil", "yeux", "indwara z amaso",
      "conjunctivitis", "conjonctivite", "pink eye",
      "vision", "blurry vision", "vision floue", "kutabona neza",
      "cataract", "cataracte",
      "glaucoma", "glaucome",
      "myopia", "myopie", "short sight", "short sightedness",
      "hyperopia", "hypermetropie", "long sight",
      "astigmatism", "astigmatisme",
      "stye", "sty", "orgelet",
      "dry eyes", "yeux secs", "amaso yumutse",
      "red eye", "oeil rouge", "amaso atukura",
      "eye pain", "douleur oculaire", "ububabare bw amaso",
      "itchy eyes", "yeux qui grattent",
      "blindness", "cecite", "impumyi",
      "strabismus", "strabisme", "crossed eyes",
      "diabetic eye", "retinopathie", "retinopathy",
      "eye discharge", "ecoulement oculaire",
      "eye disease", "maladie des yeux", "indwara y amaso",
      "eye infection", "infection oculaire",
      "poor vision", "mauvaise vision", "kutabona",
      "night blindness", "cecite nocturne",
      "double vision", "vision double", "diplopie",
      "eye pressure", "pression oculaire",
      "macular degeneration", "dmla",
      "retinal detachment", "decollement de retine",
      "uveitis", "uveite",
      "keratitis", "keratite",
      "blepharitis", "blepharite",
      "chalazion",
      "eye allergy", "allergie des yeux",
      "watery eyes", "yeux qui pleurent", "amaso arira",
      "light sensitivity", "photophobie",
      "squint", "strabisme",
      "color blindness", "daltonisme",
    ],
  },
  {
    specialization: "Orthopedics",
    feeId: 9,
    terms: [
      "fracture", "bone", "amagufwa", "os", "broken bone", "os casse", "fracture osseuse", "igufwa cyacitse",
      "back pain", "mal de dos", "umugongo", "ububabare bw umugongo", "lombalgie", "low back pain",
      "joint pain", "douleur articulaire", "arthritis", "arthrite", "arthrose", "osteoarthritis",
      "neck pain", "mal de nuque", "ijosi", "cervicalgie",
      "knee pain", "mal au genou", "ivi", "gonalgie",
      "shoulder pain", "mal a l epaule", "ibega",
      "hip pain", "mal a la hanche",
      "sprain", "entorse", "dislocation", "luxation",
      "slipped disc", "hernie discale", "herniated disc",
      "sciatica", "sciatique",
      "osteoporosis", "osteoporose",
      "sports injury", "blessure sportive",
      "ligament", "ligament tear", "tendon", "tendinite", "tendinitis",
      "carpal tunnel", "canal carpien",
      "scoliosis", "scoliose",
      "swollen joint", "articulation gonflee",
      "rheumatism", "rhumatisme",
      "bone pain", "douleur osseuse",
      "bone disease", "maladie des os", "indwara y amagufwa",
      "broken leg", "jambe cassee", "ukuguru kwacitse",
      "broken arm", "bras casse", "ukuboko kwacitse",
      "broken wrist", "poignet casse",
      "broken ankle", "cheville cassee",
      "broken hip", "hanche cassee",
      "joint swelling", "gonflement articulaire",
      "knee swelling", "genou gonfle",
      "ankle sprain", "entorse de cheville",
      "acl tear", "rupture du ligament",
      "meniscus", "menisque",
      "rotator cuff", "coiffe des rotateurs",
      "frozen shoulder", "epaule gelee",
      "tennis elbow", "epicondylite",
      "plantar fasciitis", "fasciite plantaire",
      "heel pain", "mal au talon",
      "gout joint",
      "rickets", "rachitisme",
      "clubfoot", "pied bot",
      "disc herniation",
      "cervical spondylosis", "arthrose cervicale",
      "lumbar spondylosis",
    ],
  },
  {
    specialization: "Gastroenterology",
    feeId: 22,
    terms: [
      "diarrhea", "diarrhoea", "impiswi", "diarrhee", "diarrhee aigue",
      "ulcer", "ulcere", "ulcere gastrique", "stomach ulcer", "ulcere de l estomac",
      "abdominal pain", "ububabare bwo mu nda", "mal au ventre", "mal de ventre", "douleur abdominale",
      "vomiting", "kuruka", "vomissement", "nausee", "nausea", "nausees",
      "constipation", "kwituma bigoye", "constipation chronique",
      "gastritis", "gastrite",
      "acid reflux", "reflux", "gerd", "rgo", "heartburn", "brulure d estomac", "pyrosis",
      "ibs", "syndrome de l intestin irritable", "colopathie",
      "crohn", "maladie de crohn", "colitis", "colite", "ulcerative colitis",
      "hemorrhoids", "hemorroides", "piles",
      "bloating", "ballonnement", "kugwingira",
      "jaundice", "ictere", "umwijima", "liver", "foie", "cirrhose", "cirrhosis",
      "liver disease", "liver problem", "maladie du foie", "indwara y umwijima", "umwijima urwaye",
      "liver failure", "insuffisance hepatique", "umwijima utakora",
      "liver cancer", "cancer du foie", "kanseri y umwijima", "hepatocellular carcinoma",
      "liver cirrhosis", "cirrhose du foie", "cirrhose hepatique",
      "fatty liver", "foie gras", "steatose", "steatose hepatique", "nash", "alcoholic liver", "foie alcoolique",
      "liver pain", "douleur du foie", "ububabare bw umwijima", "mal au foie",
      "liver infection", "infection du foie",
      "liver abscess", "abces hepatique",
      "swollen liver", "enlarged liver", "hepatomegalie", "umwijima wakuze",
      "hepatitis liver", "inflammation du foie",
      "ascites", "ascite", "ventre gonfle foie",
      "yellow skin", "peau jaune", "uruhu rw umuhondo", "yellow eyes", "yeux jaunes", "amaso y umuhondo",
      "bile", "bile duct", "voie biliaire", "cholestase",
      "stomach cancer", "cancer de l estomac", "kanseri y igifu",
      "colon cancer", "cancer du colon", "colorectal cancer", "cancer colorectal",
      "gastric ulcer", "ulcere gastro duodenal",
      "peptic ulcer", "ulcere peptique",
      "h pylori", "helicobacter",
      "gastroenteritis", "gastro enterite", "indwara y igifu",
      "stomach pain", "mal d estomac", "ububabare bw igifu", "igifu",
      "belly pain", "mal de ventre",
      "hernia", "hernie", "hernie inguinale", "hiatal hernia", "hernie hiatale",
      "anal fissure", "fissure anale",
      "rectal bleeding", "saignement rectal",
      "black stool", "selles noires", "melena",
      "diverticulitis", "diverticulite", "diverticulose",
      "intestinal obstruction", "occlusion intestinale",
      "giardia", "giardiase",
      "acid stomach", "acidite", "brulures d estomac",
      "gallbladder", "vesicule biliaire", "cholecystite",
      "pancreas", "pancreas", "cancer du pancreas",
      "spleen", "rate", "splenomegalie",
      "gallstones", "calculs biliaires", "vesicule",
      "pancreatitis", "pancreatite",
      "appendicitis", "appendicite",
      "blood in stool", "sang dans les selles", "rectorragie",
      "celiac", "maladie coeliaque", "gluten",
      "lactose intolerance", "intolerance au lactose",
      "indigestion", "dyspepsie", "digestion difficile",
    ],
  },
  {
    specialization: "Obstetrics & Gynecology",
    feeId: 5,
    terms: [
      "pregnancy", "pregnant", "ubutwite", "grossesse", "enceinte", "inda", "ubwite",
      "menstruation", "gynecology", "gynecologie", "periode", "regles", "menstruations", "imihango",
      "irregular period", "regles irregulieres", "amenorrhea", "amenorrhee",
      "heavy period", "menorragie", "regles abondantes",
      "pcos", "sopk", "syndrome des ovaires polykystiques", "ovaires polykystiques",
      "fibroids", "fibrome", "fibromes uterins",
      "endometriosis", "endometriose",
      "menopause",
      "infertility", "infertilite", "kutabyara",
      "family planning", "planification familiale", "contraception", "kuboneza urubyaro",
      "miscarriage", "fausse couche", "kubyara inda",
      "ectopic pregnancy", "grossesse extra uterine",
      "prenatal", "consultation prenatale", "antenatal", "isuzuma ry ubwite",
      "childbirth", "accouchement", "kubyara", "labor pain", "douleur d accouchement",
      "postnatal", "post partum", "nyuma yo kubyara",
      "vaginal discharge", "pertes vaginales", "amavuta",
      "yeast infection", "candidose", "mycose vaginale",
      "pelvic pain", "douleur pelvienne",
      "morning sickness", "nausees de grossesse",
      "bleeding in pregnancy", "saignement de grossesse",
      "breast pain", "douleur mammaire",
      "ovarian cyst", "kyste ovarien",
      "cervical", "col de l uterus",
      "cervical cancer", "cancer du col", "kanseri y inkondo",
      "breast cancer", "cancer du sein", "kanseri y ibere",
      "breast lump", "boule au sein",
      "ovarian cancer", "cancer de l ovaire",
      "uterine cancer", "cancer de l uterus",
      "period pain", "douleur de regles", "dysmenorrhee", "ububabare bw imihango",
      "menstrual cramps", "crampes menstruelles",
      "missed period", "retard de regles", "kutongera",
      "vaginal bleeding", "saignement vaginal",
      "vaginal infection", "infection vaginale",
      "pelvic inflammatory", "infection pelvienne",
      "fibroid uterus", "fibrome",
      "bartholin cyst", "kyste de bartholin",
      "ectopic", "grossesse ectopique",
      "preeclampsia", "pre eclampsie", "hypertension grossesse",
      "gestational diabetes", "diabete gestationnel", "isukari ry ubwite",
      "labor", "contractions", "contraction",
      "cesarean", "cesarienne",
      "stillbirth", "mort ne",
      "infertility female", "sterilite",
      "menopause symptoms", "bouffees de chaleur",
      "polycystic ovary", "ovaire polykystique",
    ],
  },
  {
    specialization: "Urology",
    feeId: 16,
    terms: [
      "urinary", "uti", "urine", "inkari", "urologie", "infection urinaire", "urinary tract infection",
      "painful urination", "brulure urinaire", "dysurie", "kubabara mu nkari",
      "blood in urine", "hematurie", "sang dans les urines", "amaraso mu nkari",
      "kidney stone", "calcul renal", "impyiko", "pierre au rein", "colique nephretique",
      "kidney", "rein", "kidney pain", "mal aux reins", "nephrite",
      "prostate", "prostatite", "prostate enlargement", "hypertrophie de la prostate",
      "incontinence", "incontinence urinaire", "kutabasha kwifata",
      "bladder", "vessie", "cystite", "cystitis",
      "urinary retention", "retention urinaire",
      "erectile dysfunction", "dysfonction erectile", "impuissance",
      "testicular pain", "douleur testiculaire",
      "hydrocele",
      "kidney failure", "insuffisance renale",
      "frequent urination", "mictions frequentes", "kwihagarika kenshi",
      "kidney disease", "maladie renale", "indwara y impyiko",
      "kidney infection", "infection renale", "pyelonephrite",
      "kidney failure acute", "insuffisance renale aigue",
      "renal colic", "colique renale",
      "prostate cancer", "cancer de la prostate", "kanseri ya prostate",
      "enlarged prostate", "prostate gonflee",
      "bladder infection", "infection de la vessie",
      "bladder cancer", "cancer de la vessie",
      "blood urine", "urines sanglantes",
      "burning urine", "brulure en urinant",
      "weak urine stream", "jet urinaire faible",
      "night urination", "nycturie", "kwihagarika nijoro",
      "testicle swelling", "testicule gonfle",
      "varicocele",
      "undescended testis", "cryptorchidie",
      "male infertility", "infertilite masculine",
      "painful testis", "douleur du testicule",
    ],
  },
  {
    specialization: "Pediatrics",
    feeId: 4,
    terms: [
      "child fever", "pediatric", "pediatrie", "ubuvuzi bw abana", "umwana", "enfant malade",
      "baby", "bebe", "infant", "newborn", "nouveau ne", "uruhinja", "toddler",
      "baby fever", "umuriro w umwana", "fievre bebe",
      "child cough", "toux enfant", "inkorora y umwana",
      "child diarrhea", "diarrhee enfant", "impiswi z umwana",
      "child vomiting", "vomissement enfant",
      "colic", "baby colic",
      "teething", "poussee dentaire", "amenyo y umwana",
      "diaper rash", "erytheme fessier",
      "malnutrition", "malnutrition infantile", "kwashiorkor", "imarage",
      "growth problem", "retard de croissance", "kutakura neza",
      "child vaccination", "vaccin enfant", "urukingo rw umwana",
      "child asthma",
      "croup", "laryngite enfant",
      "ear infection child", "otite enfant",
      "child rash", "eruption enfant",
      "child illness", "maladie enfant", "umwana urwaye",
      "baby jaundice", "ictere du nouveau ne",
      "baby cough", "toux du bebe",
      "baby diarrhea", "diarrhee du bebe",
      "baby vomiting", "vomissement du bebe",
      "child pneumonia", "pneumonie enfant",
      "child malaria", "malaria enfant", "malariya y umwana",
      "failure to thrive", "retard staturo ponderal",
      "rickets child", "rachitisme enfant",
      "measles child", "rougeole enfant", "seru y umwana",
      "chickenpox child", "varicelle enfant",
      "asthma child", "asthme enfant",
      "ear pain child", "mal d oreille enfant",
      "fever child", "fievre enfant",
      "convulsion child", "convulsion enfant",
      "dehydration child", "deshydratation enfant",
    ],
  },
];

function fold(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function matchDisease(query: string): DiseaseMatch | null {
  const folded = fold(query);
  if (folded.length < 3) return null;

  let best: { match: DiseaseMatch; length: number } | null = null;
  for (const entry of DISEASES) {
    for (const term of entry.terms) {
      const foldedTerm = fold(term);
      if (foldedTerm.length < 3) continue;
      const exact = folded === foldedTerm;
      const contains = folded.includes(foldedTerm);
      const hit = exact || contains;
      if (!hit) continue;
      if (!best || foldedTerm.length > best.length) {
        best = {
          match: { specialization: entry.specialization, feeId: entry.feeId },
          length: foldedTerm.length,
        };
      }
    }
  }
  return best?.match ?? null;
}

export function doctorSearchForDisease(query: string) {
  const match = matchDisease(query);
  if (!match) return null;
  const params = new URLSearchParams({
    specialization: match.specialization,
    specialization_fee_id: String(match.feeId),
    disease: "1",
    concern: query.trim(),
  });
  return `/patient/search-doctors?${params.toString()}`;
}

export type DiseaseSuggestion = DiseaseMatch & { term: string };

export function suggestDiseases(query: string, limit = 12): DiseaseSuggestion[] {
  const folded = fold(query);
  if (folded.length < 2) return [];

  const hits: Array<{ suggestion: DiseaseSuggestion; rank: number }> = [];
  const seen = new Set<string>();
  for (const entry of DISEASES) {
    for (const term of entry.terms) {
      const foldedTerm = fold(term);
      if (foldedTerm.length < 3 || seen.has(foldedTerm)) continue;
      const starts = foldedTerm.startsWith(folded);
      const includes = folded.length >= 4 && foldedTerm.includes(folded);
      if (!starts && !includes) continue;
      seen.add(foldedTerm);
      hits.push({
        suggestion: { term, specialization: entry.specialization, feeId: entry.feeId },
        rank: (starts ? 1000 : 0) - foldedTerm.length,
      });
    }
  }

  return hits
    .sort((a, b) => b.rank - a.rank)
    .slice(0, limit)
    .map((hit) => hit.suggestion);
}
